name: Cypress Tests on Windows
on: [push]

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20'


    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        run: npx cypress run
        browser: chrome
