name: Cypress Tests
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Start the server
        run: npm start

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
         
